apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-001
  labels:
    app: nginx-001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-001
  template:
    metadata:
      annotations:
        podexternalip.yglab.eu.org/externalip: 65.52.164.56    
      labels:
        app: nginx-001
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: iptables
        image: bgiddings/iptables
        command: ['sh', '-c', "sleep 3600"]
        securityContext:
          privileged: true
      - name: curl
        image: curlimages/curl
        command: ['sh', '-c', "sleep 3600"]
      initContainers:
      - name: init
        image: busybox:1.28
        command: ['sh', '-c']        
        args:
        - while ! grep -q "podexternalip.yglab.eu.org/ready" /etc/podinfo/annotations; do
            sleep 5;
          done;
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations